"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function OnboardingForm({ email, timezone }: { email: string; timezone: string }) {
  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle"); const [error, setError] = useState(""); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("saving"); setError(""); const form = new FormData(event.currentTarget); const channels = form.getAll("channels"); const response = await fetch("/api/workspace/onboarding", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessName: form.get("businessName"), businessType: form.get("businessType"), timezone: form.get("timezone"), businessEmail: form.get("businessEmail"), firstServiceName: form.get("firstServiceName"), firstServiceDuration: Number(form.get("firstServiceDuration")), channels }) }); const data = await response.json(); if (!response.ok) { setStatus("error"); setError(data.error || "We couldn’t save your setup."); return; } router.push("/dashboard"); router.refresh(); }
  return <form className="merchant-onboarding-form" onSubmit={submit}><label>Business name<input name="businessName" required placeholder="Meera's Curl Studio" /></label><label>Business type<input name="businessType" required placeholder="Salon, clinic, law firm…" /></label><div className="field-row"><label>Timezone<input name="timezone" required defaultValue={timezone} /></label><label>Notification email<input name="businessEmail" type="email" required defaultValue={email} /></label></div><div className="field-row"><label>First bookable service <span>(optional)</span><input name="firstServiceName" placeholder="Consultation" /></label><label>Duration<input name="firstServiceDuration" type="number" min="5" max="480" defaultValue="30" /></label></div><fieldset><legend>Customer channels</legend><label><input name="channels" type="checkbox" value="email" defaultChecked /> Email</label><label><input name="channels" type="checkbox" value="whatsapp" /> WhatsApp when connected</label></fieldset><button className="button button-gold" disabled={status === "saving"}>{status === "saving" ? "Creating workspace…" : "Open my dashboard"}</button>{error && <p className="form-error">{error}</p>}</form>;
}
