"use client";

import { FormEvent, useState } from "react";

type Link = { id: string; description: string; amount: number; currency: string; url: string };
export function ScheduleMessageForm({ customerId, paymentLinks }: { customerId: string; paymentLinks: Link[] }) {
  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle"); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [purpose, setPurpose] = useState<"update" | "payment_link">("update");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("saving"); setError(""); setNotice(""); const form = new FormData(event.currentTarget); const response = await fetch(`/api/customers/${customerId}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ channel: form.get("channel"), purpose, message: form.get("message"), paymentLinkId: purpose === "payment_link" ? form.get("paymentLinkId") : null, scheduledFor: new Date(String(form.get("scheduledFor"))).toISOString() }) }); const data = await response.json().catch(() => null); setStatus("idle"); if (!response.ok) { setStatus("error"); setError(data?.error || "We couldn’t schedule that update."); return; } event.currentTarget.reset(); setPurpose("update"); setNotice("Update scheduled. It will appear in the customer timeline after delivery."); }
  return <form className="payment-connect-form scheduled-message-form" onSubmit={submit}><div className="field-row"><label>Send by<select name="channel" defaultValue="email"><option value="email">Email</option><option value="whatsapp">WhatsApp template</option></select></label><label>When<input name="scheduledFor" type="datetime-local" required /></label></div><label>Purpose<select value={purpose} onChange={(event) => setPurpose(event.target.value as "update" | "payment_link")}><option value="update">Customer update</option><option value="payment_link">Payment link</option></select></label>{purpose === "payment_link" && <label>Unpaid payment link<select name="paymentLinkId" required defaultValue=""><option value="">Select a payment link</option>{paymentLinks.map((link) => <option key={link.id} value={link.id}>{link.description} · {(link.amount / 100).toFixed(2)} {link.currency}</option>)}</select></label>}<label>Message<textarea name="message" rows={4} maxLength={3000} required placeholder={purpose === "payment_link" ? "A short note to accompany the secure payment link." : "Write the customer update you want to send."} /></label><p className="form-hint">WhatsApp uses the approved template selected in Conversations. Payment links are appended securely when sent.</p><button className="button button-gold" disabled={status === "saving"}>{status === "saving" ? "Scheduling…" : "Schedule update"}</button>{notice && <p className="form-success">{notice}</p>}{error && <p className="form-error">{error}</p>}</form>;
}
