import Link from "next/link";
import { redirect } from "next/navigation";
import postgres from "postgres";
import { getCurrentSession } from "../../../lib/auth";
import { whatsappConfigured } from "../../../lib/whatsapp";
import { WhatsAppSetupForm } from "./whatsapp-setup-form";

type Conversation = { id: string; status: string; lastMessageAt: string; name: string | null; phone: string | null; latestMessage: string | null };
export default async function ConversationsPage() { const session = await getCurrentSession(); if (!session) redirect("/login"); let keyword = session.workspaceSlug; let conversations: Conversation[] = []; if (process.env.DATABASE_URL) { const sql = postgres(process.env.DATABASE_URL, { max: 1, connect_timeout: 5 }); try { const settings = await sql<{ intake_keyword: string }[]>`select intake_keyword from whatsapp_settings where workspace_id = ${session.workspaceId} limit 1`; keyword = settings[0]?.intake_keyword || keyword; conversations = await sql<Conversation[]>`select c.id, c.status, c.last_message_at as "lastMessageAt", customer.first_name as name, customer.phone, (select body from conversation_messages where conversation_id = c.id order by created_at desc limit 1) as "latestMessage" from customer_conversations c left join customers customer on customer.id = c.customer_id where c.workspace_id = ${session.workspaceId} and c.channel = 'whatsapp' order by c.last_message_at desc limit 50`; } finally { await sql.end(); } } return <main className="dashboard-page"><aside className="dashboard-nav"><Link className="wordmark" href="/">rasph<em>ia</em></Link><p>{session.workspaceName}</p><nav><Link href="/dashboard">Overview</Link><Link href={`/book/${session.workspaceSlug}`}>Booking page</Link><Link href="/dashboard/conversations">Conversations</Link><Link href="/dashboard/payments">Payments</Link></nav></aside><section className="dashboard-content"><p className="section-label">Conversations</p><h1>Every WhatsApp enquiry, in the right place.</h1><p className="dashboard-intro">Incoming messages are routed by your unique enquiry link. Rasphia records the customer and conversation, but does not send marketing messages without explicit consent.</p><WhatsAppSetupForm initialKeyword={keyword} phoneNumber={process.env.WHATSAPP_PHONE_NUMBER || ""} configured={whatsappConfigured()} /><section className="payment-offerings"><p className="section-label">Inbox</p><h2>Recent enquiries</h2>{conversations.length ? <div className="conversation-list">{conversations.map((conversation) => <article key={conversation.id}><div><b>{conversation.name || conversation.phone || "New customer"}</b><p>{conversation.latestMessage || "Media or unsupported message"}</p></div><small>{conversation.status.replace("_", " ")} · {new Date(conversation.lastMessageAt).toLocaleDateString()}</small></article>)}</div> : <p className="setup-note">New WhatsApp enquiries will appear here once a customer uses your routed link.</p>}</section></section></main>; }
