"use client";

import { FormEvent, useState } from "react";

export function WhatsAppSetupForm({ initialKeyword, phoneNumber, configured, connected }: { initialKeyword: string; phoneNumber: string; configured: boolean; connected: boolean }) {
  const [status, setStatus] = useState<"idle" | "saving" | "error">("idle"); const [error, setError] = useState(""); const [keyword, setKeyword] = useState(initialKeyword); const [editing, setEditing] = useState(!connected); const [enabled, setEnabled] = useState(connected);
  const link = phoneNumber ? `https://wa.me/${phoneNumber.replace(/\D/g, "")}?text=${encodeURIComponent(`Rasphia ${keyword}`)}` : "";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("saving"); setError(""); const response = await fetch("/api/integrations/whatsapp", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ intakeKeyword: keyword, enabled: true }) }); const data = await response.json().catch(() => null); if (!response.ok) { setStatus("error"); setError(data?.error || "We couldn’t save WhatsApp routing."); return; } setKeyword(data.intakeKeyword); setEnabled(true); setEditing(false); setStatus("idle"); }
  if (enabled && !editing) return <section className="payment-offerings whatsapp-connected"><p className="section-label">Shared Rasphia WhatsApp</p><div className="whatsapp-connected-head"><div><h2>WhatsApp routing is connected.</h2><p>Every customer who opens this link starts with your unique identifier, so their enquiry can only route to this workspace.</p></div><button className="button button-outline" type="button" onClick={() => setEditing(true)}>Edit identifier</button></div><div className="whatsapp-route"><span>Unique identifier</span><strong>Rasphia {keyword}</strong><span>Customer enquiry link</span>{link ? <a href={link} target="_blank" rel="noreferrer">{link}</a> : <p>Set `WHATSAPP_PHONE_NUMBER` to generate the share link.</p>}</div></section>;
  return <section className="payment-offerings"><p className="section-label">Shared Rasphia WhatsApp</p><h2>{enabled ? "Update your WhatsApp identifier." : "Route new enquiries safely."}</h2><p>Your identifier is unique across Rasphia. It is embedded in the customer’s first message so two businesses can never receive the same enquiry.</p><form className="payment-connect-form" onSubmit={submit}><label>Unique WhatsApp identifier<input value={keyword} onChange={(event) => setKeyword(event.target.value)} required minLength={2} pattern="[A-Za-z0-9-]+" /></label><p className="form-hint">Customers begin with: <b>Rasphia {keyword || "your-identifier"}</b></p><div className="dashboard-next-actions"><button className="button button-gold" disabled={status === "saving" || !configured}>{status === "saving" ? "Saving…" : enabled ? "Save identifier" : "Enable WhatsApp routing"}</button>{enabled && <button className="text-button" type="button" onClick={() => setEditing(false)}>Cancel</button>}</div>{!configured && <p className="form-error">The Rasphia WhatsApp account is not configured on this deployment yet.</p>}{error && <p className="form-error">{error}</p>}</form></section>;
}
