import { redirect } from "next/navigation";
import Link from "next/link";
import postgres from "postgres";
import { getCurrentSession } from "../../../lib/auth";
import { PaymentConnectForm } from "./payment-connect-form";
import { PaymentOfferingForm } from "./payment-offering-form";
import { PaymentLinkForm } from "./payment-link-form";

type Offering = { id: string; name: string; paymentType: string; amount: number; currency: string; interval: string | null };
type Connection = { provider: "stripe" | "razorpay"; currency: string; updatedAt: string };

export default async function PaymentsPage() {
  const session = await getCurrentSession(); if (!session) redirect("/login"); const origin = process.env.NEXT_PUBLIC_APP_URL || "https://www.rasphia.com"; const webhookUrls = { stripe: `${origin}/api/webhooks/stripe/${session.workspaceId}`, razorpay: `${origin}/api/webhooks/razorpay/${session.workspaceId}` };
  let offerings: Offering[] = []; let connection: Connection | null = null;
  if (process.env.DATABASE_URL) { const sql = postgres(process.env.DATABASE_URL, { max: 1, connect_timeout: 5 }); try { [offerings, connection] = await Promise.all([sql<Offering[]>`select id, name, payment_type as "paymentType", amount, currency, billing_interval as interval from payment_offerings where workspace_id = ${session.workspaceId} and active = true order by created_at desc`, sql<Connection[]>`select provider, currency, updated_at as "updatedAt" from payment_connections where workspace_id = ${session.workspaceId} and status = 'active' order by updated_at desc limit 1`.then((rows) => rows[0] || null)]); } finally { await sql.end(); } }
  return <main className="dashboard-page"><aside className="dashboard-nav"><Link className="wordmark" href="/">rasph<em>ia</em></Link><p>{session.workspaceName}</p><nav><Link href="/dashboard">Overview</Link><Link href={`/book/${session.workspaceSlug}`}>Booking page</Link><Link href="/dashboard/conversations">Conversations</Link><Link href="/dashboard/payments">Payments</Link></nav></aside><section className="dashboard-content"><div className="dashboard-heading"><div><p className="section-label">Revenue tools</p><h1>Payments, without the chasing.</h1><p className="dashboard-intro">Connect your account once, create the offers you sell, and share secure checkout links with customers.</p></div><div className={`connection-pill ${connection ? "is-connected" : ""}`}><i />{connection ? `${connection.provider === "stripe" ? "Stripe" : "Razorpay"} connected` : "No provider connected"}</div></div><div className="payment-layout"><section><PaymentConnectForm webhookUrls={webhookUrls} connection={connection} /></section><aside><p className="section-label">Before you start</p><h3>One webhook. Clear payment status.</h3><p>Add the URL shown in the connection form to your provider, then paste that endpoint’s signing secret back into Rasphia.</p><div className="payment-checklist"><span>✓ Credentials are encrypted</span><span>✓ Events are signature-verified</span><span>✓ Payment links stay in your account</span></div></aside></div><section className="payment-offerings"><p className="section-label">Step 2 of 2 · Offers</p><h2>What can customers pay for?</h2><p>Set up one-time charges, deposits, prepaid packages, or recurring memberships once. Then create a secure customer link whenever you need it.</p><PaymentOfferingForm /></section><section className="payment-offerings"><p className="section-label">Collect payment</p><h2>Create a secure customer link.</h2><p>Choose an offer, add the customer, and share their hosted checkout link by email or WhatsApp.</p><PaymentLinkForm offerings={offerings} /></section></section></main>;
}
