import { redirect } from "next/navigation";
import Link from "next/link";
import postgres from "postgres";
import { getCurrentSession } from "../../../lib/auth";
import { PaymentConnectForm } from "./payment-connect-form";
import { PaymentOfferingForm } from "./payment-offering-form";
import { PaymentLinkForm } from "./payment-link-form";

type Offering = { id: string; name: string; paymentType: string; amount: number; currency: string; interval: string | null };
export default async function PaymentsPage() { const session = await getCurrentSession(); if (!session) redirect("/login"); const origin = process.env.NEXT_PUBLIC_APP_URL || "https://rasphia.com"; let offerings: Offering[] = []; if (process.env.DATABASE_URL) { const sql = postgres(process.env.DATABASE_URL, { max: 1, connect_timeout: 5 }); try { offerings = await sql<Offering[]>`select id, name, payment_type as "paymentType", amount, currency, billing_interval as interval from payment_offerings where workspace_id = ${session.workspaceId} and active = true order by created_at desc`; } finally { await sql.end(); } } return <main className="dashboard-page"><aside className="dashboard-nav"><Link className="wordmark" href="/">rasph<em>ia</em></Link><p>{session.workspaceName}</p><nav><Link href="/dashboard">Overview</Link><Link href={`/book/${session.workspaceSlug}`}>Booking page</Link><Link href="/dashboard/payments">Payments</Link></nav></aside><section className="dashboard-content"><p className="section-label">Payments</p><h1>Get paid without the chasing.</h1><p className="dashboard-intro">Connect the merchant-owned Stripe or Razorpay account that should receive payments. Rasphia encrypts the credentials and creates payment links only from that account.</p><div className="payment-layout"><section><h2>Connect a provider</h2><PaymentConnectForm /></section><aside><p className="section-label">Webhook URLs</p><h3>Add one URL per provider.</h3><p>Use your workspace ID in the URL. Provider event signatures are verified before Rasphia updates payment status.</p><code>{origin}/api/webhooks/stripe/{session.workspaceId}</code><code>{origin}/api/webhooks/razorpay/{session.workspaceId}</code><p className="setup-note">Stripe requires its signing secret. Razorpay requires both a key ID and key secret to create links, plus a separate webhook secret.</p></aside></div><section className="payment-offerings"><p className="section-label">What customers can pay for</p><h2>Set up your offers once.</h2><p>Use the same payment system for one-time invoices, deposits, prepaid packages, and recurring memberships or retainers.</p><PaymentOfferingForm /></section><section className="payment-offerings"><p className="section-label">Collect payment</p><h2>Create a secure customer link.</h2><p>Choose an offer, then send the hosted checkout link by the channel that suits the customer.</p><PaymentLinkForm offerings={offerings} /></section></section></main>; }
