"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

type Finding = { text: string; verified: boolean };
type Category = { score: number; findings: Finding[]; fixes: string[] };
type Result = { overall: number; grade: string; discoverability: Category; ordering: Category; payments: Category };
type Audit = { jobId: string; url: string; status: "pending" | "complete" | "failed" | "timed_out"; results?: Result };
const checks = ["Checking structured data…", "Reading product and service pages…", "Looking for booking and checkout paths…", "Checking payment providers…"];

export function ScoreChecker({ initialJobId }: { initialJobId?: string }) {
  const [url, setUrl] = useState(""); const [audit, setAudit] = useState<Audit | null>(null); const [error, setError] = useState(""); const [step, setStep] = useState(0); const [email, setEmail] = useState(""); const [unlocked, setUnlocked] = useState(false); const [emailError, setEmailError] = useState("");
  useEffect(() => { if (!audit || audit.status !== "pending") return; const interval = window.setInterval(() => setStep((value) => (value + 1) % checks.length), 1800); return () => window.clearInterval(interval); }, [audit]);
  useEffect(() => { if (!audit?.jobId || audit.status !== "pending") return; let alive = true; const poll = async () => { try { const response = await fetch(`/api/ai-readiness/${audit.jobId}`); const next = await response.json(); if (!alive) return; if (!response.ok) { setError(next.error || "We couldn't retrieve this audit."); setAudit((current) => current ? { ...current, status: "failed" } : current); return; } setAudit(next); } catch { if (alive) { setError("We couldn't reach the audit service. Please try again shortly."); setAudit((current) => current ? { ...current, status: "failed" } : current); } } }; void poll(); const interval = window.setInterval(() => void poll(), 2000); return () => { alive = false; window.clearInterval(interval); }; }, [audit?.jobId, audit?.status]);
  useEffect(() => { if (audit?.status !== "pending") return; const timeout = window.setTimeout(() => setAudit((current) => current?.status === "pending" ? { ...current, status: "timed_out" } : current), 75_000); return () => window.clearTimeout(timeout); }, [audit?.status]);
  useEffect(() => { if (!initialJobId) return; void fetch(`/api/ai-readiness/${initialJobId}`).then((res) => res.ok ? res.json() : null).then((data) => data && setAudit(data)); }, [initialJobId]);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setAudit({ jobId: "", url, status: "pending" }); try { const response = await fetch("/api/ai-readiness", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "We couldn't start the check."); setAudit(null); return; } setAudit({ jobId: data.jobId || "local", url: data.url || url, status: "complete", results: data.results }); if (data.jobId) window.history.replaceState(null, "", `/ai-readiness/${data.jobId}`); } catch { setError("We couldn't reach the audit service. Please try again shortly."); setAudit(null); } }
  async function unlock(event: FormEvent) { event.preventDefault(); if (!audit) return; setEmailError(""); const response = await fetch(`/api/ai-readiness/${audit.jobId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); if (!response.ok) { const data = await response.json(); setEmailError(data.error || "Please try again."); return; } setUnlocked(true); }
  const categories: [string, string, Category][] = audit?.results ? [["AI Discoverability", "Can AI understand what you sell?", audit.results.discoverability], ["AI Booking & Ordering", "Can an agent complete the next step?", audit.results.ordering], ["AI-Native Payments", "Can an agent initiate payment?", audit.results.payments]] : [];
  return <div className="readiness-tool">
    <form className="score-form" onSubmit={submit}><label htmlFor="website">Your store website</label><div><input id="website" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="yourstore.com" inputMode="url" required /><button className="button button-gold" disabled={audit?.status === "pending"}>{audit?.status === "pending" ? "Checking…" : "Check my score"}</button></div>{error && <p className="form-error">{error}</p>}</form>
    {audit?.status === "pending" && <section className="audit-loading" aria-live="polite"><span className="loader" /><div><b>Auditing {audit.url.replace(/^https?:\/\//, "")}</b><p>{checks[step]}</p><small>This usually takes 15–30 seconds. We respect robots.txt and never guess what we can’t verify.</small></div></section>}
    {audit?.status === "failed" && <section className="audit-loading"><div><b>We couldn’t complete this check.</b><p>{error || "The site may be unreachable or block automated requests. Please try again later."}</p></div></section>}
    {audit?.status === "timed_out" && <section className="audit-loading"><div><b>This check is taking longer than expected.</b><p>We stopped waiting rather than keeping you in a loop. Try again shortly, or use a site that allows crawling.</p></div></section>}
    {audit?.status === "complete" && audit.results && <div className="audit-results"><section className="score-hero"><div className="gauge" style={{ "--score": `${audit.results.overall * 3.6}deg` } as React.CSSProperties}><span>{audit.results.overall}</span><small>/100</small></div><div><p className="section-label">Your AI Readiness Score</p><h2>Grade <em>{audit.results.grade}</em></h2><p>{audit.url.replace(/^https?:\/\//, "")} · checked just now</p></div></section><div className="score-categories">{categories.map(([name, detail, category], index) => <article className={`score-category ${!unlocked && index > 0 ? "locked" : ""}`} key={name}><div className="category-head"><div><small>{detail}</small><h3>{name}</h3></div><b>{category.score}<span>/100</span></b></div>{!unlocked && index > 0 ? <p className="locked-copy">Unlock the detailed report to see evidence and fixes.</p> : <><ul>{category.findings.slice(0, 3).map((finding) => <li className={finding.verified ? "verified" : "unverified"} key={finding.text}>{finding.text}</li>)}</ul><div className="fixes"><small>Top fixes</small>{category.fixes.map((fix) => <p key={fix}>{fix}</p>)}</div></>}</article>)}</div>{!unlocked && <form className="unlock" onSubmit={unlock}><div><p className="section-label">Unlock the full report</p><h3>Get every finding and your highest-impact fixes.</h3></div><div><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@business.com" required /><button className="button button-dark">Unlock report</button>{emailError && <p className="form-error">{emailError}</p>}</div></form>}<Link className="migrate-cta" href="/#start"><span>Rasphia stores score 90+ by default</span><b>Migrate your store →</b></Link></div>}
  </div>;
}
