import { Resend } from "resend";

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] || character);

export async function sendBookingEmails(input: { businessName: string; senderSlug: string; merchantEmail: string; customerEmail: string; customerName: string; serviceName: string; startsAt: Date; timezone: string; status: "requested" | "confirmed" }) {
  if (!process.env.RESEND_API_KEY) return { customerId: null, merchantId: null };
  const date = new Intl.DateTimeFormat("en", { dateStyle: "full", timeStyle: "short", timeZone: input.timezone }).format(input.startsAt);
  const from = `${input.businessName} via Rasphia <${input.senderSlug}@rasphia.com>`;
  const resend = new Resend(process.env.RESEND_API_KEY);
  const heading = input.status === "confirmed" ? "Your booking is confirmed" : "We received your booking request";
  const [customer, merchant] = await Promise.allSettled([
    resend.emails.send({ from, to: input.customerEmail, subject: `${heading}: ${input.serviceName} · ${input.businessName}`, html: `<main style="max-width:620px;margin:0 auto;padding:28px;background:#f5f3ed;color:#132e32;font:16px/1.5 Arial,sans-serif"><p style="margin:0;color:#55706c;font-size:12px;letter-spacing:.08em;text-transform:uppercase">${escapeHtml(input.businessName)}</p><h1 style="margin:8px 0 14px;font:36px/1.05 Georgia,serif">${heading}</h1><p>Hi ${escapeHtml(input.customerName)},</p><p>${input.status === "confirmed" ? "Your appointment is on the calendar. Please arrive a few minutes early." : "The business has received your request and will confirm the time shortly."}</p><section style="padding:18px;background:#fff;border:1px solid #d6ddd8;border-radius:10px"><b>Service</b><br/>${escapeHtml(input.serviceName)}<br/><br/><b>Date and time</b><br/>${escapeHtml(date)}<br/><br/><b>Time zone</b><br/>${escapeHtml(input.timezone)}</section><p>${input.status === "confirmed" ? "If you need to change the appointment, reply to this email or contact the business directly." : "You will receive another update when the business confirms your request."}</p></main>` }),
    resend.emails.send({ from, to: input.merchantEmail, subject: `Action needed · ${input.status === "confirmed" ? "Booking confirmed" : "New booking request"} · ${input.customerName}`, html: `<main style="max-width:620px;margin:0 auto;padding:28px;background:#f5f3ed;color:#132e32;font:16px/1.5 Arial,sans-serif"><p style="margin:0;color:#55706c;font-size:12px;letter-spacing:.08em;text-transform:uppercase">Rasphia booking alert</p><h1 style="margin:8px 0 14px;font:36px/1.05 Georgia,serif">${input.status === "confirmed" ? "Booking added to the calendar" : "New booking request"}</h1><p><b>${escapeHtml(input.customerName)}</b> ${input.status === "confirmed" ? "booked" : "requested"} <b>${escapeHtml(input.serviceName)}</b>.</p><section style="padding:18px;background:#fff;border:1px solid #d6ddd8;border-radius:10px"><b>Date and time</b><br/>${escapeHtml(date)}<br/><br/><b>Customer email</b><br/>${escapeHtml(input.customerEmail)}</section><p>${input.status === "confirmed" ? "The customer has been sent the appointment details." : "Review the request and contact the customer if you need to confirm or adjust the time."}</p></main>` }),
  ]);
  if (customer.status === "rejected") console.error("Customer booking email failed", customer.reason);
  if (merchant.status === "rejected") console.error("Merchant booking email failed", merchant.reason);
  return { customerId: customer.status === "fulfilled" ? customer.value.data?.id || null : null, merchantId: merchant.status === "fulfilled" ? merchant.value.data?.id || null : null };
}
