import type { Research, Strategy } from "./business-diagnosis";

const esc = (value: string) => value.replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[c] || c);
const list = (items: string[]) => items.map((item) => "<li>" + esc(item) + "</li>").join("");

export function strategyShareReportHtml(research: Research, report: Strategy) {
  const plays = report.plays.map((play) => "<article><small>" + esc(play.pillar) + "</small><h2>" + esc(play.title) + "</h2><p><b>Signals</b>" + esc(play.signals) + "</p><p><b>Play</b>" + esc(play.action) + "</p><p><b>Why</b>" + esc(play.why) + "</p><p><b>Cost</b>" + esc(play.cost) + "</p><p><b>What good looks like</b>" + esc(play.goodLooks) + "</p></article>").join("");
  const support = report.implementationSupport.map((item) => "<article><h3>" + esc(item.service) + "</h3><p>" + esc(item.outcome) + "</p></article>").join("");
  const score = research.aiReadiness ? '<section class="score"><b>' + research.aiReadiness.overall + '</b><span> / 100 readiness</span><p>Discoverability ' + research.aiReadiness.discoverability.score + ' · Booking ' + research.aiReadiness.ordering.score + ' · Payments ' + research.aiReadiness.payments.score + '</p></section>' : '';
  return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' + esc(research.name) + ' — Business Diagnosis</title><style>body{margin:0;background:#f5f3ed;color:#132e32;font:16px/1.55 Arial}.wrap{max-width:960px;margin:auto;padding:42px 24px}.brand,.label{font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:#55706c}.hero{padding:25px 0;border-bottom:1px solid #ccd8d3}.hero h1{margin:8px 0;font:clamp(42px,6vw,70px)/.95 Georgia}.hero p{max-width:650px;color:#55706c}.score{margin:25px 0;padding:20px;border-radius:12px;background:#e4eeea}.score b{font:48px Georgia}.score p{color:#405a56}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.grid article{padding:20px;border:1px solid #d6ddd8;border-radius:12px;background:#fff}.grid h2,.grid h3{margin:8px 0;font:25px Georgia}.grid p{color:#5a706d;font-size:14px}.grid p b{display:block;color:#132e32;font-size:11px;text-transform:uppercase}.support{padding:20px;border-radius:12px;background:#173f3d;color:#fff}.support article{border-color:#41625d;background:transparent}.support p{color:#d9e8e1}.skip{margin:24px 0;padding:16px;border-left:3px solid #cda752;background:#fff8e6}.bottom{display:grid;grid-template-columns:1fr 1fr;gap:20px}.bottom h2{font:26px Georgia}@media(max-width:720px){.grid,.bottom{grid-template-columns:1fr}.wrap{padding:28px 18px}}</style></head><body><main class="wrap"><p class="brand">Rasphia / Business Diagnosis</p><header class="hero"><h1>' + esc(research.name) + '</h1><p>' + esc(report.summary) + '</p></header>' + score + '<p class="label">Highest-ROI plays</p><section class="grid">' + plays + '</section><p class="label">How Rasphia can build this with you</p><section class="grid support">' + support + '</section><p class="skip"><b>What to skip:</b> ' + esc(report.whatToSkip) + '</p><section class="bottom"><article><h2>Your first week</h2><ol>' + list(report.firstWeek) + '</ol></article><article><h2>Watchouts</h2><ul>' + list(report.watchouts) + '</ul></article></section></main></body></html>';
}
