import { redirect } from "next/navigation";
import Link from "next/link";
import postgres from "postgres";
import { getCurrentSession } from "../../lib/auth";

export default async function DashboardPage({ searchParams }: { searchParams?: Promise<{ error?: string; calendar?: string }> }) {
  const session = await getCurrentSession();
  if (!session) redirect("/login");
  if (session.onboardingStatus !== "complete") redirect("/dashboard/onboarding");
  let setup = { calendar: false, whatsapp: false, payments: false, booking: false };
  if (process.env.DATABASE_URL) {
    const sql = postgres(process.env.DATABASE_URL, { max: 1, connect_timeout: 5 });
    try {
      const checks = await Promise.allSettled([
        sql`select 1 from google_calendar_connections where workspace_id = ${session.workspaceId} limit 1`,
        sql`select 1 from whatsapp_settings where workspace_id = ${session.workspaceId} and enabled = true limit 1`,
        sql`select 1 from payment_connections where workspace_id = ${session.workspaceId} limit 1`,
        sql`select 1 from booking_services where workspace_id = ${session.workspaceId} and active = true limit 1`,
      ]);
      const connected = (result: PromiseSettledResult<unknown>) => result.status === "fulfilled" && Array.isArray(result.value) && result.value.length > 0;
      setup = { calendar: connected(checks[0]), whatsapp: connected(checks[1]), payments: connected(checks[2]), booking: connected(checks[3]) };
    } catch { /* The setup experience remains usable while a new workspace is migrating. */ } finally { await sql.end(); }
  }
  const completed = Object.values(setup).filter(Boolean).length;
  const query = searchParams ? await searchParams : {};
  const next = !setup.calendar ? { title: "Connect the calendar that runs your day.", copy: "Confirm native bookings on Google Calendar and keep your team’s availability in one place.", href: "/api/integrations/google-calendar", action: "Connect Google Calendar" } : !setup.whatsapp ? { title: "Bring WhatsApp enquiries into one inbox.", copy: "Create a unique enquiry link, then route every new customer conversation to this workspace.", href: "/dashboard/conversations", action: "Set up WhatsApp" } : !setup.booking ? { title: "Give customers a clear way to book.", copy: "Add your first service so your public booking page is ready to share.", href: "/dashboard/booking", action: "Edit booking page" } : !setup.payments ? { title: "Your customer engine is taking shape.", copy: "Connect payments when you are ready to collect deposits, packages, or recurring memberships.", href: "/dashboard/payments", action: "Set up payments" } : { title: "Your customer engine is ready to run.", copy: "Your calendar, conversations, booking page, and payment connection are all set up.", href: "/dashboard/booking", action: "Open booking page" };
  return <main className="dashboard-page"><DashboardNav name={session.workspaceName} slug={session.workspaceSlug} completed={completed} /><section className="dashboard-content dashboard-overview">{query.error && <p className="form-error dashboard-alert">{query.error}</p>}{query.calendar === "connected" && <p className="form-success dashboard-alert">Google Calendar connected successfully.</p>}<header className="overview-header"><div><p className="section-label">Workspace overview</p><h1>Good to see you, {session.name?.split(" ")[0] || "there"}.</h1><p className="dashboard-intro">A calm place to turn every enquiry into the next right customer action.</p></div><div className="setup-progress"><span>{completed}<small>/4 connected</small></span><p>Setup progress</p></div></header><section className="dashboard-metrics" aria-label="Workspace connections"><article className={setup.calendar ? "is-ready" : ""}><span>Calendar</span><b>{setup.calendar ? "Connected" : "Not connected"}</b><small>{setup.calendar ? "Bookings can land in Google Calendar" : "Sync availability and appointments"}</small></article><article className={setup.whatsapp ? "is-ready" : ""}><span>WhatsApp</span><b>{setup.whatsapp ? "Connected" : "Not connected"}</b><small>{setup.whatsapp ? "Customer enquiries route to your inbox" : "Route customer conversations"}</small></article><article className={setup.booking ? "is-ready" : ""}><span>Booking page</span><b>{setup.booking ? "Ready" : "Needs a service"}</b><small>{setup.booking ? "Your public booking page is shareable" : "Add what customers can book"}</small></article><article className={setup.payments ? "is-ready" : ""}><span>Payments</span><b>{setup.payments ? "Connected" : "Optional"}</b><small>{setup.payments ? "Ready for payment links" : "Collect payments when you need to"}</small></article></section><section className="dashboard-next"><div><p className="section-label">Recommended next step</p><h2>{next.title}</h2><p>{next.copy}</p></div><div className="dashboard-next-actions">{next.href.startsWith("/api/") ? <a className="button button-gold" href={next.href}>{next.action}</a> : <Link className="button button-gold" href={next.href}>{next.action}</Link>}<Link className="dashboard-link" href={`/book/${session.workspaceSlug}`}>Open booking page ↗</Link></div></section></section></main>;
}

function DashboardNav({ name, slug, completed }: { name: string; slug: string; completed: number }) { return <aside className="dashboard-nav"><div className="dashboard-brand"><Link className="wordmark" href="/">rasph<em>ia</em></Link><span className="workspace-mark">R</span></div><div className="workspace-card"><span>Workspace</span><strong>{name}</strong><small>{completed}/4 essentials connected</small></div><nav aria-label="Dashboard navigation"><p>Workspace</p><Link className="active" href="/dashboard"><i>⌂</i>Overview</Link><Link href={`/book/${slug}`}><i>↗</i>Booking page</Link><Link href="/dashboard/conversations"><i>◌</i>Conversations</Link><Link href="/dashboard/customers"><i>◒</i>Customers</Link><Link href="/dashboard/settings"><i>⚙</i>Settings</Link><p>Grow revenue</p><Link href="/dashboard/payments"><i>◇</i>Payments</Link><Link href="/dashboard/workflows"><i>✦</i>Automations <small>Beta</small></Link></nav><div className="dashboard-nav-foot"><Link href="/" className="dashboard-home-link">← Back to Rasphia</Link><form action="/api/auth/signout" method="post"><button type="submit">Sign out</button></form></div></aside>; }
