"use client";

import { FormEvent, useState } from "react";

type Service = { id: string; name: string; description: string | null; duration: number };
export function BookingForm({ slug, services }: { slug: string; services: Service[] }) {
  const [status, setStatus] = useState<"idle" | "sending" | "success" | "error">("idle"); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const startsAt = form.get("startsAt") as string; setStatus("sending"); setError(""); const response = await fetch("/api/public/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug, serviceId: form.get("serviceId"), startsAt: startsAt ? new Date(startsAt).toISOString() : "", name: form.get("name"), email: form.get("email"), phone: form.get("phone"), note: form.get("note"), emailConsent: form.get("emailConsent") === "on", whatsappConsent: form.get("whatsappConsent") === "on" }) }); const data = await response.json(); if (!response.ok) { setStatus("error"); setError(data.error || "We couldn’t create your booking."); return; } setStatus("success"); }
  if (!services.length) return <p className="booking-empty">This business has not added bookable services yet.</p>;
  if (status === "success") return <div className="booking-success"><span>✓</span><h2>Your request is in.</h2><p>Check your email for the details. The business will confirm your time shortly.</p></div>;
  return <form className="public-booking-form" onSubmit={submit}><label>Choose a service<select name="serviceId" required defaultValue=""><option value="" disabled>Select a service</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name} · {service.duration} min</option>)}</select></label><label>Preferred time<input name="startsAt" type="datetime-local" required /></label><div className="field-row"><label>Your name<input name="name" required autoComplete="name" /></label><label>Email<input name="email" type="email" required autoComplete="email" /></label></div><label>Phone<input name="phone" type="tel" required autoComplete="tel" /></label><label>Anything the business should know? <span>(optional)</span><textarea name="note" rows={3} /></label><label className="consent"><input name="emailConsent" type="checkbox" required defaultChecked /> I agree to receive booking updates by email.</label><label className="consent"><input name="whatsappConsent" type="checkbox" required /> I agree to receive booking updates on WhatsApp.</label><button className="button button-gold" disabled={status === "sending"}>{status === "sending" ? "Sending request…" : "Request this time"}</button>{error && <p className="form-error">{error}</p>}</form>;
}
